# Generated by Django 4.0.2 on 2022-06-10 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_num_name', models.CharField(max_length=100, verbose_name='Semester')),
            ],
        ),
        migrations.CreateModel(
            name='StdYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_code', models.CharField(blank=True, max_length=15, null=True)),
                ('year_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'University Year',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subj_name', models.CharField(max_length=100)),
                ('subj_credit', models.FloatField()),
                ('total_mark', models.FloatField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_age', models.PositiveIntegerField(blank=True, null=True)),
                ('student_father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('date_of_joining', models.DateField(default=django.utils.timezone.now, verbose_name='Admission')),
                ('student_image', models.FileField(blank=True, default='student-image/person_avatar.png', upload_to='student-image/')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.semester', verbose_name='Semester')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='student_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.stdyear', verbose_name='Year'),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_code', models.CharField(blank=True, max_length=20, null=True)),
                ('obtained_mark', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
            ],
        ),
    ]
